# 开发环境配置（简化版）
spring:
  # 使用 H2 内存数据库进行快速测试
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  
  # Redis 配置 - 暂时注释掉
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     database: 0
  #     timeout: 5000ms
  
  # Kafka 配置 - 暂时注释掉
  # kafka:
  #   bootstrap-servers: localhost:9092
  
  # 邮件配置 - 暂时注释掉
  # mail:
  #   host: smtp.gmail.com

# 自定义配置
kisesaki:
  blog:
    # JWT 配置
    jwt:
      secret: kisesaki-blog-jwt-secret-key-for-development-only
      expiration: 86400000 # 24小时
      refresh-expiration: 604800000 # 7天

# 日志配置
logging:
  level:
    com.kisesaki.blog: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
