interface Permission {
  name: string;
  description: string;
  resource: string;
  action: string;
  level: string;
  note: string;
}

export const PERMISSIONS: Permission[] = [
  // 文章管理权限
  {
    name: 'POST_CREATE',
    description: '创建文章',
    resource: 'post',
    action: 'create',
    level: '用户级',
    note: '用户可以创建新文章',
  },
  {
    name: 'POST_EDIT_OWN',
    description: '编辑自己的文章',
    resource: 'post',
    action: 'edit_own',
    level: '用户级',
    note: '只能编辑自己创建的文章',
  },
  {
    name: 'POST_EDIT_ALL',
    description: '编辑所有文章',
    resource: 'post',
    action: 'edit_all',
    level: '管理员级',
    note: '可以编辑任何用户的文章',
  },
  {
    name: 'POST_DELETE_OWN',
    description: '删除自己的文章',
    resource: 'post',
    action: 'delete_own',
    level: '用户级',
    note: '只能删除自己创建的文章',
  },
  {
    name: 'POST_DELETE_ALL',
    description: '删除所有文章',
    resource: 'post',
    action: 'delete_all',
    level: '管理员级',
    note: '可以删除任何用户的文章',
  },
  {
    name: 'POST_PUBLISH',
    description: '发布文章',
    resource: 'post',
    action: 'publish',
    level: '管理员级',
    note: '发布/取消发布文章',
  },
  {
    name: 'POST_MANAGE',
    description: '管理文章',
    resource: 'post',
    action: 'manage',
    level: '管理员级',
    note: '文章的高级管理操作（置顶、精选等）',
  },
  {
    name: 'POST_VIEW_ALL',
    description: '查看所有文章',
    resource: 'post',
    action: 'view_all',
    level: '管理员级',
    note: '查看包含草稿在内的所有文章',
  },
  {
    name: 'POST_REVISION_VIEW',
    description: '查看文章版本',
    resource: 'post',
    action: 'revision_view',
    level: '用户级',
    note: '查看文章版本历史',
  },
  {
    name: 'POST_REVISION_RESTORE',
    description: '恢复文章版本',
    resource: 'post',
    action: 'revision_restore',
    level: '用户级',
    note: '恢复文章到指定版本',
  },
  // 评论管理权限
  {
    name: 'COMMENT_CREATE',
    description: '创建评论',
    resource: 'comment',
    action: 'create',
    level: '用户级',
    note: '用户可以发表评论',
  },
  {
    name: 'COMMENT_EDIT_OWN',
    description: '编辑自己的评论',
    resource: 'comment',
    action: 'edit_own',
    level: '用户级',
    note: '只能编辑自己的评论',
  },
  {
    name: 'COMMENT_DELETE_OWN',
    description: '删除自己的评论',
    resource: 'comment',
    action: 'delete_own',
    level: '用户级',
    note: '只能删除自己的评论',
  },
  {
    name: 'COMMENT_DELETE_ALL',
    description: '删除所有评论',
    resource: 'comment',
    action: 'delete_all',
    level: '管理员级',
    note: '可以删除任何人的评论',
  },
  {
    name: 'COMMENT_MODERATE',
    description: '评论审核',
    resource: 'comment',
    action: 'moderate',
    level: '管理员级',
    note: '评论审核和管理',
  },
  // 用户管理权限
  {
    name: 'USER_MANAGE',
    description: '用户管理',
    resource: 'user',
    action: 'manage',
    level: '管理员级',
    note: '用户管理的总权限',
  },
  {
    name: 'USER_VIEW_ALL',
    description: '查看用户列表',
    resource: 'user',
    action: 'view_all',
    level: '管理员级',
    note: '查看所有用户信息',
  },
  {
    name: 'USER_BAN',
    description: '禁用用户',
    resource: 'user',
    action: 'ban',
    level: '管理员级',
    note: '禁用/解禁用户账号',
  },
  {
    name: 'USER_UNBAN',
    description: '解禁用户',
    resource: 'user',
    action: 'unban',
    level: '管理员级',
    note: '解除用户禁用状态',
  },
  {
    name: 'USER_EDIT',
    description: '编辑用户信息',
    resource: 'user',
    action: 'edit',
    level: '管理员级',
    note: '编辑用户基本信息',
  },
  {
    name: 'USER_DELETE',
    description: '删除用户',
    resource: 'user',
    action: 'delete',
    level: '管理员级',
    note: '删除用户账号',
  },
  // 分类管理权限
  {
    name: 'CATEGORY_VIEW',
    description: '查看分类',
    resource: 'category',
    action: 'view',
    level: '管理员级',
    note: '查看分类管理界面',
  },
  {
    name: 'CATEGORY_CREATE',
    description: '创建分类',
    resource: 'category',
    action: 'create',
    level: '管理员级',
    note: '创建新分类',
  },
  {
    name: 'CATEGORY_EDIT',
    description: '编辑分类',
    resource: 'category',
    action: 'edit',
    level: '管理员级',
    note: '编辑现有分类',
  },
  {
    name: 'CATEGORY_DELETE',
    description: '删除分类',
    resource: 'category',
    action: 'delete',
    level: '管理员级',
    note: '删除分类',
  },
  // 标签管理权限
  {
    name: 'TAG_CREATE',
    description: '创建标签',
    resource: 'tag',
    action: 'create',
    level: '用户级',
    note: '用户可以创建新标签',
  },
  {
    name: 'TAG_EDIT',
    description: '编辑标签',
    resource: 'tag',
    action: 'edit',
    level: '管理员级',
    note: '编辑现有标签',
  },
  {
    name: 'TAG_DELETE',
    description: '删除标签',
    resource: 'tag',
    action: 'delete',
    level: '管理员级',
    note: '删除标签',
  },
  {
    name: 'TAG_MANAGE',
    description: '管理标签',
    resource: 'tag',
    action: 'manage',
    level: '管理员级',
    note: '标签的高级管理操作',
  },
  // 文件管理权限
  {
    name: 'FILE_UPLOAD',
    description: '上传文件',
    resource: 'file',
    action: 'upload',
    level: '用户级',
    note: '用户可以上传文件',
  },
  {
    name: 'FILE_DELETE_OWN',
    description: '删除自己的文件',
    resource: 'file',
    action: 'delete_own',
    level: '用户级',
    note: '只能删除自己上传的文件',
  },
  {
    name: 'FILE_DELETE_ALL',
    description: '删除所有文件',
    resource: 'file',
    action: 'delete_all',
    level: '管理员级',
    note: '可以删除任何文件',
  },
  {
    name: 'FILE_VIEW_ALL',
    description: '查看所有文件',
    resource: 'file',
    action: 'view_all',
    level: '管理员级',
    note: '查看所有用户上传的文件',
  },
  // 通知管理权限
  {
    name: 'NOTIFICATION_SEND',
    description: '发送通知',
    resource: 'notification',
    action: 'send',
    level: '管理员级',
    note: '发送系统通知',
  },
  {
    name: 'NOTIFICATION_MANAGE',
    description: '管理通知',
    resource: 'notification',
    action: 'manage',
    level: '管理员级',
    note: '管理通知设置',
  },
  // 订阅管理权限
  {
    name: 'SUBSCRIPTION_MANAGE',
    description: '管理订阅',
    resource: 'subscription',
    action: 'manage',
    level: '管理员级',
    note: '管理用户订阅',
  },
  {
    name: 'NEWSLETTER_SEND',
    description: '发送新闻通讯',
    resource: 'newsletter',
    action: 'send',
    level: '管理员级',
    note: '发送邮件新闻通讯',
  },
  // 系统管理权限
  {
    name: 'SYSTEM_STATS_VIEW',
    description: '查看系统统计',
    resource: 'system',
    action: 'stats_view',
    level: '管理员级',
    note: '查看系统统计数据',
  },
  {
    name: 'SYSTEM_CONFIG_MANAGE',
    description: '管理系统配置',
    resource: 'system',
    action: 'config_manage',
    level: '管理员级',
    note: '管理系统配置',
  },
  {
    name: 'SYSTEM_MONITOR',
    description: '系统监控',
    resource: 'system',
    action: 'monitor',
    level: '管理员级',
    note: '系统性能监控',
  },
  {
    name: 'SYSTEM_BACKUP',
    description: '数据备份',
    resource: 'system',
    action: 'backup',
    level: '管理员级',
    note: '执行数据备份',
  },
  {
    name: 'SYSTEM_RESTORE',
    description: '数据恢复',
    resource: 'system',
    action: 'restore',
    level: '管理员级',
    note: '执行数据恢复',
  },
  // SEO管理权限
  {
    name: 'SEO_MANAGE',
    description: '管理SEO设置',
    resource: 'seo',
    action: 'manage',
    level: '管理员级',
    note: '管理SEO相关设置',
  },
  // 重定向管理权限
  {
    name: 'REDIRECT_MANAGE',
    description: '管理重定向',
    resource: 'redirect',
    action: 'manage',
    level: '管理员级',
    note: '管理URL重定向规则',
  },
  // 举报管理权限
  {
    name: 'REPORT_HANDLE',
    description: '处理举报',
    resource: 'report',
    action: 'handle',
    level: '管理员级',
    note: '处理用户举报',
  },
  {
    name: 'REPORT_VIEW',
    description: '查看举报',
    resource: 'report',
    action: 'view',
    level: '管理员级',
    note: '查看举报列表',
  },
  // 审计权限
  {
    name: 'AUDIT_VIEW',
    description: '查看审计日志',
    resource: 'audit',
    action: 'view',
    level: '管理员级',
    note: '查看系统审计日志',
  },
  {
    name: 'DATA_EXPORT',
    description: '导出数据',
    resource: 'data',
    action: 'export',
    level: '管理员级',
    note: '导出系统数据',
  },
  // 分析权限
  {
    name: 'ANALYTICS_VIEW',
    description: '查看分析数据',
    resource: 'analytics',
    action: 'view',
    level: '管理员级',
    note: '查看网站分析数据',
  },
  {
    name: 'ANALYTICS_MANAGE',
    description: '管理分析配置',
    resource: 'analytics',
    action: 'manage',
    level: '管理员级',
    note: '管理分析工具配置',
  },
  // 仪表板权限
  {
    name: 'DASHBOARD_ADMIN_ACCESS',
    description: '管理员仪表板访问',
    resource: 'dashboard',
    action: 'admin_access',
    level: '管理员级',
    note: '访问管理员仪表板',
  },
];
